In [2]:
import pandas as pd
import numpy as np

In [3]:
2) For the given numpy arrays, Array1 and Array2, what will be the dot product for the same. 
Array1 = array([[1, 2, 3], [4, 5, 6]]) 
Array2 = array([[2, 3],[3, 2]])


Valueerror          # Answer
Keyerror
array([[ -9, 6, -1],[-12, 18, -7]])
None of the Above

In [10]:
from array import array
Array1 = np.array([[1, 2, 3], [4, 5, 6]]) 
Array2 = np.array([[2, 3],[3, 2]])

In [12]:
np.dot(Array1,Array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
np.dot(Array2,Array1)


array([[14, 19, 24],
       [11, 16, 21]])

In [14]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])

In [15]:
array[::-1]       #ANwer


array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [16]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [18]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3)) 


In [19]:
C=np.dot(a, b)

In [20]:
C.ndim

6

In [21]:
C[2,3,2,1,2,2]

499128

In [22]:
C

array([[[[[[  5220,   5205,   5190],
           [  4950,   4935,   4920],
           [  4680,   4665,   4650],
           [  4410,   4395,   4380]],

          [[  4140,   4125,   4110],
           [  3870,   3855,   3840],
           [  3600,   3585,   3570],
           [  3330,   3315,   3300]],

          [[  3060,   3045,   3030],
           [  2790,   2775,   2760],
           [  2520,   2505,   2490],
           [  2250,   2235,   2220]],

          [[  1980,   1965,   1950],
           [  1710,   1695,   1680],
           [  1440,   1425,   1410],
           [  1170,   1155,   1140]],

          [[   900,    885,    870],
           [   630,    615,    600],
           [   360,    345,    330],
           [    90,     75,     60]]],


         [[[ 17874,  17823,  17772],
           [ 16956,  16905,  16854],
           [ 16038,  15987,  15936],
           [ 15120,  15069,  15018]],

          [[ 14202,  14151,  14100],
           [ 13284,  13233,  13182],
           [ 12366,  123

In [23]:
C.shape

(3, 4, 5, 5, 4, 3)

In [24]:
C.size

3600

In [25]:
a = np.array([3, 7, 32], dtype = complex) 
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [26]:
np.random.seed(100) 
ar1 = np.random.uniform(1,50, 20)

In [27]:
np.clip(ar1, a_min=10, a_max=30)


array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [28]:
np.where(ar1 < 10, 10, np.where(ar1 > 30, 30, ar1))

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [29]:
array1 = np.array([[1,2],[3,4]]) 
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [31]:
np.vstack((array1,array2))

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [32]:
np.hstack((array1,array2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 5

In [ ]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])  
Elem_to_be_inserted = [1,2,3,4] 

In [33]:
np.insert(array,4,[1,2,3,4])

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [35]:
array1 = np.array([10,3,1,203,404,204,20,302,30,402,192])  
array2= [1,2,3,4] 

In [37]:
np.insert(array2, np.index(404), array2)


AttributeError: module 'numpy' has no attribute 'index'

In [39]:
np.insert(array1, np.where(404), array2)


ValueError: index array argument obj to insert must be one dimensional or scalar

In [40]:
np.insert(array1, 4, array2)

array([ 10,   3,   1, 203,   1,   2,   3,   4, 404, 204,  20, 302,  30,
       402, 192])

In [43]:
np.full((3,3),"k")


array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [45]:
np.random.random((3,3), "k")


TypeError: random() takes at most 1 positional argument (2 given)

In [55]:
def bub_sort(array): 
    for i in range(0, len(array)): 
        for j in range(0, len(array) - i - 1): 
            if array[j] < array[j + 1]: 
                temp = array[j] 
                array[j] = array[j + 1] 
                array[j+1] = temp 
    return array 
my_array = np.array([20,14,25,16,45,60,12,9])

In [56]:
my_array

array([20, 14, 25, 16, 45, 60, 12,  9])

In [57]:
print(bub_sort(my_array))

[60 45 25 20 16 14 12  9]


In [72]:
np.arange(5,2)


array([], dtype=int32)

In [59]:
np.reshape(my_array,(2,4))

array([[60, 45, 25, 20],
       [16, 14, 12,  9]])

In [62]:
np.shape(my_array,(4,2))

TypeError: _shape_dispatcher() takes 1 positional argument but 2 were given

In [63]:
my_array

array([60, 45, 25, 20, 16, 14, 12,  9])

In [64]:
my_array.shape=(4,2)

In [65]:
my_array

array([[60, 45],
       [25, 20],
       [16, 14],
       [12,  9]])

In [66]:
my_array.shape=(4,2,1)

In [67]:
my_array

array([[[60],
        [45]],

       [[25],
        [20]],

       [[16],
        [14]],

       [[12],
        [ 9]]])

In [70]:
np.reshape(my_array,(2,5) == (5,2))


TypeError: an integer is required

In [73]:
Sample = np.array([[1,2],[3,4],[5,6],[7,8]])

In [77]:
S=np.ravel(Sample)
S

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
S.shape

(8,)

In [83]:
Sample.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
Sample.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [86]:
type(S)

numpy.ndarray

In [87]:
#array([2, 5, 8])
Sample = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])


In [88]:
Sample[0:3, 1]

array([2, 5, 8])

In [89]:
Sample[[0:3], [1]]

SyntaxError: invalid syntax (2688566331.py, line 1)

In [90]:
Sample[0:3][1]


array([4, 5, 6])

In [101]:
Array1 = np.arange(20,2) 
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(Array1)
print(Array2)

[]
[ 1  2  3  4  5  6  7  8  9 10]


In [102]:
np.hstack((Array1,Array2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
Array1 = np.arange(1,20,2) 
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(Array1)
print(Array2)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  2  3  4  5  6  7  8  9 10]


In [104]:
np.hstack((Array1,Array2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [108]:
Array1 = np.arange(1,20,2) 
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(Array1)
print(Array2)
np.column_stack((Array1,Array2))

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  1],
       [ 3,  2],
       [ 5,  3],
       [ 7,  4],
       [ 9,  5],
       [11,  6],
       [13,  7],
       [15,  8],
       [17,  9],
       [19, 10]])

In [109]:
array1 = np.array([[1,2],[3,4]]) 
array2 = np.array([[5,6],[7,8]])

In [111]:
np.column_stack((array1,array2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [160]:
A = np.array([[4],[12],[29]]) 
B = np.array([[13],[21],[4]])

In [161]:
print(A,A.shape)
print("--"*10)
print(B,B.shape)

[[ 4]
 [12]
 [29]] (3, 1)
--------------------
[[13]
 [21]
 [ 4]] (3, 1)


In [163]:
np.cross(A,B,axis=0)

array([[-561],
       [ 361],
       [ -72]])

In [145]:
np.dot(A,B)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [125]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) 
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])


In [126]:
np.corrcoef(A,B)

array([[1., 1.],
       [1., 1.]])

In [128]:
sample = {1: [1,2], 2: [[1],[2]], 3: [[1,2], [3,4], [4,5]], 4: [1], 5: [1,2,3,4,5]}

In [129]:
np.array(sample)

array({1: [1, 2], 2: [[1], [2]], 3: [[1, 2], [3, 4], [4, 5]], 4: [1], 5: [1, 2, 3, 4, 5]},
      dtype=object)

In [130]:

arr1= np.array([[3,2,1],[6,4,5],[8,7,9]]) 


In [131]:
np.max(arr1,axis=0)-np.min(arr1,axis=1)

array([7, 3, 2])