In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
a=np.array((1,2,3,4,5,6))

In [4]:
a         # by passing the tuple and the list 

array([1, 2, 3, 4, 5, 6])

In [5]:
a.ndim

1

In [6]:
a.shape

(6,)

In [7]:
a.size

6

In [8]:
a.itemsize

4

In [9]:
a.nbytes

24

In [10]:
a.dtype

dtype('int32')

In [11]:
type(a)

numpy.ndarray

In [12]:
a.data

In [13]:
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(3,30)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
np.arange(3,30,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [17]:
np.arange(0,25,(5,5))

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [18]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [20]:
np.linspace(0,100,50).reshape(10,5)

array([[  0.        ,   2.04081633,   4.08163265,   6.12244898,
          8.16326531],
       [ 10.20408163,  12.24489796,  14.28571429,  16.32653061,
         18.36734694],
       [ 20.40816327,  22.44897959,  24.48979592,  26.53061224,
         28.57142857],
       [ 30.6122449 ,  32.65306122,  34.69387755,  36.73469388,
         38.7755102 ],
       [ 40.81632653,  42.85714286,  44.89795918,  46.93877551,
         48.97959184],
       [ 51.02040816,  53.06122449,  55.10204082,  57.14285714,
         59.18367347],
       [ 61.2244898 ,  63.26530612,  65.30612245,  67.34693878,
         69.3877551 ],
       [ 71.42857143,  73.46938776,  75.51020408,  77.55102041,
         79.59183673],
       [ 81.63265306,  83.67346939,  85.71428571,  87.75510204,
         89.79591837],
       [ 91.83673469,  93.87755102,  95.91836735,  97.95918367,
        100.        ]])

In [21]:
np.linspace(0,100,50,dtype=int)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [23]:
np.linspace(0,100,50,dtype=int).reshape(10,5)

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69],
       [ 71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89],
       [ 91,  93,  95,  97, 100]])

In [24]:
b=np.linspace(0,100,50,dtype=int).reshape(10,5)
b

array([[  0,   2,   4,   6,   8],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48],
       [ 51,  53,  55,  57,  59],
       [ 61,  63,  65,  67,  69],
       [ 71,  73,  75,  77,  79],
       [ 81,  83,  85,  87,  89],
       [ 91,  93,  95,  97, 100]])

In [25]:
b.shape

(10, 5)

In [26]:
b.size

50

In [27]:
b.itemsize

4

In [28]:
b.nbytes

200

In [29]:
b.dtype

dtype('int32')

In [30]:
type(b)

numpy.ndarray

In [31]:
C=np.linspace(0,100,50,dtype=complex).reshape(10,5)


In [32]:
C

array([[  0.        +0.j,   2.04081633+0.j,   4.08163265+0.j,
          6.12244898+0.j,   8.16326531+0.j],
       [ 10.20408163+0.j,  12.24489796+0.j,  14.28571429+0.j,
         16.32653061+0.j,  18.36734694+0.j],
       [ 20.40816327+0.j,  22.44897959+0.j,  24.48979592+0.j,
         26.53061224+0.j,  28.57142857+0.j],
       [ 30.6122449 +0.j,  32.65306122+0.j,  34.69387755+0.j,
         36.73469388+0.j,  38.7755102 +0.j],
       [ 40.81632653+0.j,  42.85714286+0.j,  44.89795918+0.j,
         46.93877551+0.j,  48.97959184+0.j],
       [ 51.02040816+0.j,  53.06122449+0.j,  55.10204082+0.j,
         57.14285714+0.j,  59.18367347+0.j],
       [ 61.2244898 +0.j,  63.26530612+0.j,  65.30612245+0.j,
         67.34693878+0.j,  69.3877551 +0.j],
       [ 71.42857143+0.j,  73.46938776+0.j,  75.51020408+0.j,
         77.55102041+0.j,  79.59183673+0.j],
       [ 81.63265306+0.j,  83.67346939+0.j,  85.71428571+0.j,
         87.75510204+0.j,  89.79591837+0.j],
       [ 91.83673469+0.j,  93.8775510

In [34]:
C.dtype

dtype('complex128')

In [35]:
C.nbytes

800

In [36]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [38]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((3,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [43]:
np.zeros((3,2,5),dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [39]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.ones(3)

array([1., 1., 1.])

In [41]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [44]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [45]:
np.zeros((2,3,4),dtype=complex)

array([[[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]])

In [46]:
np.full((3,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [47]:
np.full(3,7)

array([7, 7, 7])

In [48]:
np.full(3,2,7)

TypeError: Cannot interpret '7' as a data type

In [49]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [51]:
np.full((3,4),7,order="F")

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [53]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
np.empty(3)

array([0., 0., 0.])

In [55]:
np.empty(10,dtype=int)

array([1294230768,        366, 1343381888,        366, 1343382016,
              366, 1667853427,  741353573, 1667853427,  741550181])

In [56]:
D=np.arange(24).reshape(2,3,4)
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [57]:
np.reshape(D,-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [58]:
D

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
D.reshape(-1)       # above and this way both works fine 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
E=D.reshape(-1)
E

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [63]:
import sys
np.set_printoptions(threshold=sys.maxsize)

In [64]:
dir(sys)

['__breakpointhook__',
 '__displayhook__',
 '__doc__',
 '__excepthook__',
 '__interactivehook__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__stderr__',
 '__stdin__',
 '__stdout__',
 '__unraisablehook__',
 '_base_executable',
 '_clear_type_cache',
 '_current_frames',
 '_debugmallocstats',
 '_enablelegacywindowsfsencoding',
 '_framework',
 '_getframe',
 '_git',
 '_home',
 '_xoptions',
 'addaudithook',
 'api_version',
 'argv',
 'audit',
 'base_exec_prefix',
 'base_prefix',
 'breakpointhook',
 'builtin_module_names',
 'byteorder',
 'call_tracing',
 'copyright',
 'displayhook',
 'dllhandle',
 'dont_write_bytecode',
 'exc_info',
 'excepthook',
 'exec_prefix',
 'executable',
 'exit',
 'flags',
 'float_info',
 'float_repr_style',
 'get_asyncgen_hooks',
 'get_coroutine_origin_tracking_depth',
 'getallocatedblocks',
 'getdefaultencoding',
 'getfilesystemencodeerrors',
 'getfilesystemencoding',
 'getprofile',
 'getrecursionlimit',
 'getrefcount',
 'getsizeof',
 'getswitchinterva

In [65]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [66]:
a-b

array([20, 29, 38, 47])

In [67]:
np.subtract(a,b)

array([20, 29, 38, 47])

In [68]:
np.add(a,b)

array([20, 31, 42, 53])

In [69]:
a+1

array([21, 31, 41, 51])

In [70]:
a

array([20, 30, 40, 50])

In [71]:
a-10

array([10, 20, 30, 40])

In [72]:
a**2

array([ 400,  900, 1600, 2500], dtype=int32)

In [73]:
np.exp(a)

array([4.85165195e+08, 1.06864746e+13, 2.35385267e+17, 5.18470553e+21])

In [75]:
np.power(a,5)

array([  3200000,  24300000, 102400000, 312500000], dtype=int32)

In [76]:
pow(5,2)   # normally it works but it doesnot works for array we have to use power instead of pow

25

In [77]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [78]:
np.sin(a)*10

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [80]:
x=np.array([[1,1],[0,1]])
y=np.array([[2,0],[3,4]])
print(x)
print(y)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [83]:
x*y

array([[2, 0],
       [0, 4]])

In [84]:
x@y

array([[5, 4],
       [3, 4]])

In [85]:
np.dot(x,y)         np.dot(x,y) and the x@y are the dot products of the x and y

array([[5, 4],
       [3, 4]])

In [86]:
np.cross(x,y)

array([-2, -3])

In [87]:
x = [1, 2, 0]
y = [4, 5, 6]
np.cross(x, y)

array([12, -6, -3])

In [88]:
#Both vectors with dimension 2.
x = [1,2]
y = [4,5]
np.cross(x, y)

array(-3)

In [90]:
x=[1,2,3]
y=[4,5,6]
np.cross(x,y)

array([-3,  6, -3])

In [91]:
x=[1,2]
y=[4,5]
np.cross(x,y)

array(-3)

In [92]:
x*y

TypeError: can't multiply sequence by non-int of type 'list'

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'list'

In [94]:
np.exp(x,5)

TypeError: return arrays must be of ArrayType

In [95]:
np.pow(x,2)

AttributeError: module 'numpy' has no attribute 'pow'

In [96]:
np.power(x,2)

array([1, 4], dtype=int32)

In [97]:
x

[1, 2]

In [100]:
ar=np.array([21,54,1656,6,6,6,61,61,646,1,616,46,6,6,2,44,14,698,34,684,1465])

In [101]:
np.sort(ar)

array([   1,    2,    6,    6,    6,    6,    6,   14,   21,   34,   44,
         46,   54,   61,   61,  616,  646,  684,  698, 1465, 1656])

In [102]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [103]:
ar1=np.sort(ar)
ar1

array([   1,    2,    6,    6,    6,    6,    6,   14,   21,   34,   44,
         46,   54,   61,   61,  616,  646,  684,  698, 1465, 1656])

In [104]:
np.lexsort(ar) # dont know what is it doing

0

In [105]:
a = [1,5,1,4,3,4,4] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [106]:
a = [1,5,1,4,3,4,4,2] # First column
b = [9,4,0,4,0,2,1] # Second column
ind = np.lexsort((b,a)) # Sort by a, then by b
ind

ValueError: all keys need to be the same shape

In [107]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [108]:
np.argsort(ar)     # give the indeices after sorting the array

array([ 9, 14,  3,  4,  5, 12, 13, 16,  0, 18, 15, 11,  1,  6,  7, 10,  8,
       19, 17, 20,  2], dtype=int64)

In [113]:
np.searchsorted(ar,5)

0

In [114]:
np.searchsorted(ar1,5)         # since the ar1 is sorted form of ar array

2

In [115]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [118]:
ar2=np.partition(ar,10)

In [119]:
ar2

array([   6,    2,   34,    6,    6,    6,    6,   21,   14,    1,   44,
         46,   54,   61,   61,  616,  646,  698, 1656,  684, 1465])

In [121]:
ar3=np.partition(ar,11)
ar3

array([   6,    2,   34,    6,    6,    6,    6,   21,   14,    1,   44,
         46,   54,   61,   61,  616,  646,  698, 1656,  684, 1465])

In [122]:
arr1=np.array([1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17])
arr1

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [123]:
np.partition(arr1,10)

array([ 2,  1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [124]:
arr1=np.array([1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,1,2,3,4,5,10])
arr1

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,  1,
        2,  3,  4,  5, 10])

In [125]:
np.partition(arr1,10)

array([ 1,  1,  2,  2,  4,  5,  5,  3,  4,  6,  7,  8,  9, 10, 16, 17, 15,
       14, 13, 11, 10, 12])

In [126]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
np.concatenate((a, b.T), axis=1)


array([[1, 2, 5],
       [3, 4, 6]])

In [128]:
np.concatenate((a, b), axis=None)


array([1, 2, 3, 4, 5, 6])

In [129]:
a.ndim

2

In [130]:
a.shape

(2, 2)

In [131]:
a.size

4

In [132]:
a.itemsize

4

In [134]:
a.nbytes

16

In [135]:
a.base

In [136]:
b.base

In [137]:
print(a.base)

None


In [138]:
print(b.base)

None


In [139]:
a.any

<function ndarray.any>

In [141]:
print(a.any())

True


In [142]:
a.all()

True

In [144]:
a.argmax()

3

In [145]:
a.argmin()

0

In [146]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [148]:
ar.argpartition(10)

array([12, 14, 18,  3,  4,  5, 13,  0, 16,  9, 15, 11,  1,  6,  7, 10,  8,
       17,  2, 19, 20], dtype=int64)

In [149]:
ar.astype(dtype=float)

array([2.100e+01, 5.400e+01, 1.656e+03, 6.000e+00, 6.000e+00, 6.000e+00,
       6.100e+01, 6.100e+01, 6.460e+02, 1.000e+00, 6.160e+02, 4.600e+01,
       6.000e+00, 6.000e+00, 2.000e+00, 4.400e+01, 1.400e+01, 6.980e+02,
       3.400e+01, 6.840e+02, 1.465e+03])

In [150]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [151]:
ar.astype(float)

array([2.100e+01, 5.400e+01, 1.656e+03, 6.000e+00, 6.000e+00, 6.000e+00,
       6.100e+01, 6.100e+01, 6.460e+02, 1.000e+00, 6.160e+02, 4.600e+01,
       6.000e+00, 6.000e+00, 2.000e+00, 4.400e+01, 1.400e+01, 6.980e+02,
       3.400e+01, 6.840e+02, 1.465e+03])

In [152]:
ar.byteswap()   #Swap the bytes of the array elements
"""
Toggle between low-endian and big-endian data representation by
returning a byteswapped array, optionally swapped in-place.
Arrays of byte-strings are not swapped. The real and imaginary
parts of a complex number are swapped individually.
"""

array([  352321536,   905969664,  2013659136,   100663296,   100663296,
         100663296,  1023410176,  1023410176, -2046689280,    16777216,
        1744961536,   771751936,   100663296,   100663296,    33554432,
         738197504,   234881024, -1174274048,   570425344, -1409155072,
       -1190854656])

In [158]:
ar.clip(10,100)

array([ 21,  54, 100,  10,  10,  10,  61,  61, 100,  10, 100,  46,  10,
        10,  10,  44,  14, 100,  34, 100, 100])

In [159]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [160]:
np.clip(ar,10,100)

array([ 21,  54, 100,  10,  10,  10,  61,  61, 100,  10, 100,  46,  10,
        10,  10,  44,  14, 100,  34, 100, 100])

In [161]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [162]:
np.compress(ar,ar>10) # dont know it is correct or not

array([ True,  True,  True, False, False, False,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True])

In [163]:
ar.cumprod()

array([         21,        1134,     1877904,    11267424,    67604544,
         405627264, -1026540672,  1805528448, -1859727104, -1859727104,
        1164371968,  2021502976,  -755884032,  -240336896,  -480673792,
         325189632,   257687552,  -522715136,  -592445440, -1505755136,
        1681915904], dtype=int32)

In [164]:
np.cumprod(ar)

array([         21,        1134,     1877904,    11267424,    67604544,
         405627264, -1026540672,  1805528448, -1859727104, -1859727104,
        1164371968,  2021502976,  -755884032,  -240336896,  -480673792,
         325189632,   257687552,  -522715136,  -592445440, -1505755136,
        1681915904], dtype=int32)

In [165]:
np.prod(ar)

1681915904

In [166]:
ar.cumsum()

array([  21,   75, 1731, 1737, 1743, 1749, 1810, 1871, 2517, 2518, 3134,
       3180, 3186, 3192, 3194, 3238, 3252, 3950, 3984, 4668, 6133],
      dtype=int32)

In [167]:
ar.data

In [171]:
ar.diagonal()

ValueError: diag requires an array of at least two dimensions

In [173]:
ar2=np.array([1,2,3,4,5,6,7,8,10,11,12,9,8,7,6,5])
ar2

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [178]:
ar2=ar2.reshape(4,4)

In [179]:
np.diagonal(ar2)

array([ 1,  6, 12,  5])

In [180]:
ar2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 11, 12,  9],
       [ 8,  7,  6,  5]])

In [181]:
ar2=ar2.reshape(2,2,4)

In [182]:
ar2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [184]:
np.diagonal(ar2)

array([[1, 8],
       [2, 7],
       [3, 6],
       [4, 5]])

In [188]:
ar.dtype

dtype('int32')

In [189]:
ar

array([  21,   54, 1656,    6,    6,    6,   61,   61,  646,    1,  616,
         46,    6,    6,    2,   44,   14,  698,   34,  684, 1465])

In [190]:
ar.fill(10)

In [191]:
ar

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10])

In [193]:
np.fill(ar,12)

AttributeError: module 'numpy' has no attribute 'fill'

In [194]:
ar.fill(0)        # it would not work with np.fill

In [195]:
ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [197]:
ar.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [200]:
np.flags(ar)

AttributeError: module 'numpy' has no attribute 'flags'

In [202]:
ar2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [203]:
np.flat(ar2)

AttributeError: module 'numpy' has no attribute 'flat'

In [206]:
ar2.flat()

TypeError: 'numpy.flatiter' object is not callable

In [207]:
ar2.flat

In [208]:
list(ar2.flat)

[1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 9, 8, 7, 6, 5]

In [209]:
def vikas(a):
    return a*a
b=list(map(vikas,ar2.flat))

In [210]:
b

[1, 4, 9, 16, 25, 36, 49, 64, 100, 121, 144, 81, 64, 49, 36, 25]

In [211]:
def vikas(a):
    return a*a
b=list(map(vikas,ar2))

In [212]:
b

[array([[ 1,  4,  9, 16],
        [25, 36, 49, 64]]),
 array([[100, 121, 144,  81],
        [ 64,  49,  36,  25]])]

In [213]:
ar2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [214]:
ar2.flatten

<function ndarray.flatten>

In [215]:
ar2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [216]:
ar2

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [217]:
np.flatten(ar2)

AttributeError: module 'numpy' has no attribute 'flatten'

In [220]:
ar2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [221]:
np.flatten(ar2)

AttributeError: module 'numpy' has no attribute 'flatten'

In [222]:
ar2.flat()

TypeError: 'numpy.flatiter' object is not callable

In [223]:
np.flat(ar2)

AttributeError: module 'numpy' has no attribute 'flat'

In [224]:
np.ravel(ar2)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [225]:
ar2.flatten

<function ndarray.flatten>

In [227]:
list(ar2.flatten())

[1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 9, 8, 7, 6, 5]

In [228]:
ar2.flat()

TypeError: 'numpy.flatiter' object is not callable

In [229]:
np.flat(ar2)

AttributeError: module 'numpy' has no attribute 'flat'

In [232]:
np.flatiter(ar2)

TypeError: cannot create 'numpy.flatiter' instances

In [234]:
ar2.imag()

TypeError: 'numpy.ndarray' object is not callable

In [235]:
ar2.item

<function ndarray.item>

In [236]:
ar2.item()

ValueError: can only convert an array of size 1 to a Python scalar

In [237]:
ar2.itemsize

4

In [238]:
ar2.itemsize()

TypeError: 'int' object is not callable

In [239]:
np.itemsize(ar2)

AttributeError: module 'numpy' has no attribute 'itemsize'

In [240]:
ar2.itemsize

4

In [241]:
ar2.itemsize()

TypeError: 'int' object is not callable

In [242]:
ar2.itemsize()

TypeError: 'int' object is not callable

In [244]:
ar2.min()

1

In [245]:
ar2.max()

12

In [247]:
np.min(ar2),np.max(ar2)

(1, 12)

In [249]:
ar2.nbytes,           ar2.ndim

(64, 3)

In [250]:
np.nbytes(ar2)

TypeError: '_typedict' object is not callable

In [251]:
np.ndim(ar2)         # ndim works with np but the nbytes are not in the numpy profile

3

In [253]:
ar2.newbyteorder()

array([[[ 16777216,  33554432,  50331648,  67108864],
        [ 83886080, 100663296, 117440512, 134217728]],

       [[167772160, 184549376, 201326592, 150994944],
        [134217728, 117440512, 100663296,  83886080]]])

In [254]:
np.newbyteorder(ar2)

AttributeError: module 'numpy' has no attribute 'newbyteorder'

In [255]:
ar2.nonzero()

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [256]:
np.nonzero(ar2)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [257]:
ar2.ptp()          #Peak to peak (maximum - minimum) value along a given axis.

11

In [258]:
ar2                       # ptp --- peak to peak means here 12-1=11

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [259]:
np.ptp(ar2)

11

In [262]:
np.partition(ar,10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [263]:
ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [264]:
ar1

array([   1,    2,    6,    6,    6,    6,    6,   14,   21,   34,   44,
         46,   54,   61,   61,  616,  646,  684,  698, 1465, 1656])

In [266]:
np.partition(ar1,10)

array([   2,    1,    6,    6,    6,    6,    6,   14,   21,   34,   44,
         46,   54,   61,   61,  616,  646,  684,  698, 1465, 1656])

In [267]:
ar2.partition(10)

ValueError: kth(=10) out of bounds (4)

In [270]:
ar.partition(5)

In [271]:
ar1

array([   1,    2,    6,    6,    6,    6,    6,   14,   21,   34,   44,
         46,   54,   61,   61,  616,  646,  684,  698, 1465, 1656])

In [272]:
ar1.partition(5)

In [273]:
print(ar1.partition(5))

None


In [274]:
ar2.prod()

1563803648

In [275]:
np.prod(ar2)

1563803648

In [279]:
ar2.ravel()

array([ 1,  5,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [280]:
np.ravel(ar2)

array([ 1,  5,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [281]:
ar2

array([[[ 1,  5,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [282]:
ar2.reshape(-1)

array([ 1,  5,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [283]:
np.reshape(ar2,-1)

array([ 1,  5,  3,  4,  5,  6,  7,  8, 10, 11, 12,  9,  8,  7,  6,  5])

In [284]:
ar2.real()

TypeError: 'numpy.ndarray' object is not callable

In [285]:
np.real(ar2)

array([[[ 1,  5,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [287]:
ar2.astype(dtype=float)

array([[[ 1.,  5.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12.,  9.],
        [ 8.,  7.,  6.,  5.]]])

In [288]:
ar22=ar2.astype(dtype=float)
ar22

array([[[ 1.,  5.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12.,  9.],
        [ 8.,  7.,  6.,  5.]]])

In [289]:
np.real(ar22)

array([[[ 1.,  5.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[10., 11., 12.,  9.],
        [ 8.,  7.,  6.,  5.]]])

In [290]:
ar23=np.array([[1.12,2.51,3.114,6.545],[7.121,8.55,.922,4.56]])
ar23

array([[1.12 , 2.51 , 3.114, 6.545],
       [7.121, 8.55 , 0.922, 4.56 ]])

In [291]:
np.real(ar23)

array([[1.12 , 2.51 , 3.114, 6.545],
       [7.121, 8.55 , 0.922, 4.56 ]])

In [294]:
ar23=ar23.astype(dtype=complex)

In [295]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [7.121+0.j, 8.55 +0.j, 0.922+0.j, 4.56 +0.j]])

In [296]:
np.real(ar23)        # it works in the complex which extract out the real part of it only

array([[1.12 , 2.51 , 3.114, 6.545],
       [7.121, 8.55 , 0.922, 4.56 ]])

In [298]:
ar23.real()

TypeError: 'numpy.ndarray' object is not callable

In [299]:
ar23.repeat()

TypeError: repeat() missing required argument 'repeats' (pos 1)

In [301]:
np.repeat(ar23,4)

array([1.12 +0.j, 1.12 +0.j, 1.12 +0.j, 1.12 +0.j, 2.51 +0.j, 2.51 +0.j,
       2.51 +0.j, 2.51 +0.j, 3.114+0.j, 3.114+0.j, 3.114+0.j, 3.114+0.j,
       6.545+0.j, 6.545+0.j, 6.545+0.j, 6.545+0.j, 7.121+0.j, 7.121+0.j,
       7.121+0.j, 7.121+0.j, 8.55 +0.j, 8.55 +0.j, 8.55 +0.j, 8.55 +0.j,
       0.922+0.j, 0.922+0.j, 0.922+0.j, 0.922+0.j, 4.56 +0.j, 4.56 +0.j,
       4.56 +0.j, 4.56 +0.j])

In [302]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [303]:
np.repeat(5,100)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [304]:
ap=np.array([0,2,5,6])

In [305]:
ap

array([0, 2, 5, 6])

In [306]:
np.repeat(ap,5)

array([0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6])

In [307]:
np.repeat([10,2],5)

array([10, 10, 10, 10, 10,  2,  2,  2,  2,  2])

In [308]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [7.121+0.j, 8.55 +0.j, 0.922+0.j, 4.56 +0.j]])

In [310]:
ar23.resize(2,2,2)

In [311]:
ar23

array([[[1.12 +0.j, 2.51 +0.j],
        [3.114+0.j, 6.545+0.j]],

       [[7.121+0.j, 8.55 +0.j],
        [0.922+0.j, 4.56 +0.j]]])

In [313]:
np.resize(ar23,(2,4))

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [7.121+0.j, 8.55 +0.j, 0.922+0.j, 4.56 +0.j]])

In [314]:
ar23

array([[[1.12 +0.j, 2.51 +0.j],
        [3.114+0.j, 6.545+0.j]],

       [[7.121+0.j, 8.55 +0.j],
        [0.922+0.j, 4.56 +0.j]]])

In [315]:
ar23.resize(2,4)

In [316]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [7.121+0.j, 8.55 +0.j, 0.922+0.j, 4.56 +0.j]])

In [317]:
ar23.size

8

In [318]:
np.size(ar23)

8

In [320]:
ar23.sort()

In [321]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [0.922+0.j, 4.56 +0.j, 7.121+0.j, 8.55 +0.j]])

In [322]:
ar2

array([[[ 1,  5,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 11, 12,  9],
        [ 8,  7,  6,  5]]])

In [323]:
ar2.sort()

In [324]:
ar2

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [325]:
np.sort(ar2)

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [326]:
np.sort(ar2,axis=1)

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [327]:
ar2

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [328]:
np.squeeze(ar2)

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [329]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [330]:
np.squeeze(x).shape


(3,)

In [331]:
np.squeeze(x, axis=0).shape

(3, 1)

In [332]:
np.squeeze(x, axis=1).shape

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [333]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [0.922+0.j, 4.56 +0.j, 7.121+0.j, 8.55 +0.j]])

In [334]:
ar2

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [335]:
ar2.std()

2.8442650632456883

In [336]:
np.std(ar2)

2.8442650632456883

In [337]:
ar2.strides

(32, 16, 4)

In [339]:
ar2.strides()

TypeError: 'tuple' object is not callable

In [340]:
a.strides

(8, 4)

In [341]:
b.strides

AttributeError: 'list' object has no attribute 'strides'

In [342]:
b

[array([[ 1,  4,  9, 16],
        [25, 36, 49, 64]]),
 array([[100, 121, 144,  81],
        [ 64,  49,  36,  25]])]

In [343]:
a

array([[1, 2],
       [3, 4]])

In [344]:
ar2

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [345]:
ar2.strides

(32, 16, 4)

In [346]:
ar2.sum()

107

In [347]:
np.sum(ar2)

107

In [351]:
np.swapaxes(ar2,axis1)

NameError: name 'axis1' is not defined

In [352]:
np.swapaxes(ar2,0,1)


array([[[ 1,  3,  4,  5],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [ 5,  6,  7,  8]]])

In [353]:
np.swapaxes(ar2,1,0)


array([[[ 1,  3,  4,  5],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [ 5,  6,  7,  8]]])

In [354]:
np.swapaxes(ar23,1,0)


array([[1.12 +0.j, 0.922+0.j],
       [2.51 +0.j, 4.56 +0.j],
       [3.114+0.j, 7.121+0.j],
       [6.545+0.j, 8.55 +0.j]])

In [355]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [0.922+0.j, 4.56 +0.j, 7.121+0.j, 8.55 +0.j]])

In [356]:
np.swapaxes(ar23,0,1)


array([[1.12 +0.j, 0.922+0.j],
       [2.51 +0.j, 4.56 +0.j],
       [3.114+0.j, 7.121+0.j],
       [6.545+0.j, 8.55 +0.j]])

In [357]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [0.922+0.j, 4.56 +0.j, 7.121+0.j, 8.55 +0.j]])

In [358]:
ar23.T

array([[1.12 +0.j, 0.922+0.j],
       [2.51 +0.j, 4.56 +0.j],
       [3.114+0.j, 7.121+0.j],
       [6.545+0.j, 8.55 +0.j]])

In [359]:
ar2

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [360]:
ar2.T

array([[[ 1,  9],
        [ 5,  5]],

       [[ 3, 10],
        [ 6,  6]],

       [[ 4, 11],
        [ 7,  7]],

       [[ 5, 12],
        [ 8,  8]]])

In [361]:
ar2.take(5)

6

In [362]:
ar2.take(10)

11

In [363]:
np.take(ar2,5)

6

In [364]:
ar2.tobytes()

b'\x01\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\n\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00'

In [365]:
np.tobytes(ar2)

AttributeError: module 'numpy' has no attribute 'tobytes'

In [367]:
ar2.tolist()

[[[1, 3, 4, 5], [5, 6, 7, 8]], [[9, 10, 11, 12], [5, 6, 7, 8]]]

In [368]:
np.tolist(ar2)

AttributeError: module 'numpy' has no attribute 'tolist'

In [369]:
ar2.trace()      #Return the sum along diagonals of the array.

array([ 6,  9, 11, 13])

In [370]:
ar2

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [371]:
np.trace(ar2)

array([ 6,  9, 11, 13])

In [374]:
ar2.transpose()

array([[[ 1,  9],
        [ 5,  5]],

       [[ 3, 10],
        [ 6,  6]],

       [[ 4, 11],
        [ 7,  7]],

       [[ 5, 12],
        [ 8,  8]]])

In [376]:
ar2.view()

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [378]:
ar=ar2.view()

In [379]:
ar

array([[[ 1,  3,  4,  5],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]]])

In [380]:
ar23

array([[1.12 +0.j, 2.51 +0.j, 3.114+0.j, 6.545+0.j],
       [0.922+0.j, 4.56 +0.j, 7.121+0.j, 8.55 +0.j]])