In [1]:
import numpy

In [2]:
my_array=numpy.array([[[[1,3,4]]]])

In [3]:
my_array.ndim

4

In [4]:
A=numpy.array(my_array,ndmin=5)      # Answer is  1. a

In [5]:
A.ndim

5

In [9]:
Array1 = numpy.array([[1, 2, 3], [4, 5, 6]])
Array2 = numpy.array([[2, 3],[3, 2]])

In [10]:
numpy.dot(Array1,Array2)                  # Answer2. b ValueError

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [11]:
import numpy as np
array = np.array([10,3,1,203,404,204,20,302,30,402,192])

In [12]:
array

array([ 10,   3,   1, 203, 404, 204,  20, 302,  30, 402, 192])

In [13]:
array[::-1]

array([192, 402,  30, 302,  20, 204, 404, 203,   1,   3,  10])

In [14]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

In [15]:
np.dot(a, b)             # Answer 4. b

array([[4, 1],
       [2, 2]])

In [16]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))

In [17]:
np.dot(a, b)[2,3,2,1,2,2]       # Answer 5. a 499128

499128

In [18]:
a = np.array([3, 7, 32], dtype = complex)            # Answer 6. a
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [19]:
a=np.random.seed(100)
ar1 = np.random.uniform(1,50, 20)

In [20]:
ar1

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [21]:
np.where(ar1 < 10, 10, np.where(ar1 > 30, 30, ar1))          # ANSWER 7. b

array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

In [22]:
array1 = np.array([10,3,1,203,404,204,20,302,30,402,192])# here we rename as array1 and array2 as they are now according to ques
array2 = [1,2,3,4]

In [23]:
numpy.insert(array2, 404, array2)

IndexError: index 404 is out of bounds for axis 0 with size 4

In [ ]:
numpy.insert(array2, np.index(404), array2)

In [ ]:
numpy.insert(array1, np.where(404), array2)

In [ ]:
numpy.insert(array1, 4, array2)          #ANSWER 8. D

In [24]:
np.full((3,3),"k")

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [25]:
def bub_sort(array):
    for i in range(0, len(array)):
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j+1] = temp
    return array
array = numpy.array([20,14,25,16,45,60,12,9])


In [26]:
print(bub_sort(array))                # ANSWER 10. b

[60 45 25 20 16 14 12  9]


In [27]:
a=np.array([[20,14,25,16,45],[60,12,9,45,6]])
a

array([[20, 14, 25, 16, 45],
       [60, 12,  9, 45,  6]])

In [28]:
np.reshape(a,(5,2))   #  numpy.reshape(5,2)     #Answer 11.d if numpy.reshape(a,(5,2)

array([[20, 14],
       [25, 16],
       [45, 60],
       [12,  9],
       [45,  6]])

In [29]:
Sample = numpy.array([[1,2],[3,4],[5,6],[7,8]])
Sample

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [30]:
np.ravel(Sample)              # ANSWER  12. a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
Sample = numpy.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])

In [32]:
Sample

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [33]:
Sample[0:3,1]      # ANSWER 13. A

array([2, 5, 8])

In [34]:
Array1 =np.arange(1,20,2)               # Array1  should be like that  otherwise answer would be D
Array2 =np.array([1,2,3,4,5,6,7,8,9,10])

In [35]:
print(Array1)
print(Array2)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  2  3  4  5  6  7  8  9 10]


In [36]:
np.hstack((Array1,Array2))         # answer is 14. A           if the Array1=numpy.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

In [37]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

In [38]:
np.row_stack((array1,array2))         # Answer  15.a

array([[ 1,  2],
       [ 3,  4],
       [ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [39]:
array1 = np.array([[1,2],[3,4]])
array2 = np.array([[5,6],[7,8]])

In [40]:
print(array1)
print(array2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [41]:
np.column_stack((array1,array2))                #ANSWER 16.a

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [42]:
A = np.array([[4],[12],[29]])
B = np.array([[13],[21],[4]])

In [43]:
print(A)
print(B)

[[ 4]
 [12]
 [29]]
[[13]
 [21]
 [ 4]]


In [44]:
np.cross(A,B,axis=0)         #Answer 17. A

array([[-561],
       [ 361],
       [ -72]])

In [45]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

In [46]:
np.corrcoef(A,B)               # ANSWER 18. A

array([[1., 1.],
       [1., 1.]])

In [47]:
sample = {1: [1,2],2: [[1],[2]],3: [[1,2], [3,4], [4,5]],4: [1],5: [1,2,3,4,5]}

In [48]:
sample

{1: [1, 2],
 2: [[1], [2]],
 3: [[1, 2], [3, 4], [4, 5]],
 4: [1],
 5: [1, 2, 3, 4, 5]}

In [49]:
np.array([[1, list([1, 2])], [2, list([[1], [2]])], [3, list([[1, 2], [3, 4], [4, 5]])], [4, list([1])], [5, list([1,
2, 3, 4, 5])]], dtype=object)

array([[1, list([1, 2])],
       [2, list([[1], [2]])],
       [3, list([[1, 2], [3, 4], [4, 5]])],
       [4, list([1])],
       [5, list([1, 2, 3, 4, 5])]], dtype=object)

In [50]:
#answer 19. a

In [51]:
import random

In [52]:
a=np.random.randint(1,10,(3,3))
a

array([[4, 8, 2],
       [2, 8, 8],
       [1, 3, 4]])

In [53]:
b=np.max(a,axis=0)
b

array([4, 8, 8])

In [54]:
c=np.min(a,axis=1)
c

array([2, 2, 1])

In [55]:
np.subtract(b,c)

array([2, 6, 7])